# Form implementation generated from reading ui file 'c:\Users\Dartencet\Documents\GitHub\projetprogrammation2021\modules\modules_IHM\IHM_en_Qt\4EdTPatient.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(720, 615)
        self.Retour_commandLinkButton = QtWidgets.QCommandLinkButton(Form)
        self.Retour_commandLinkButton.setGeometry(QtCore.QRect(0, 520, 222, 48))
        self.Retour_commandLinkButton.setObjectName("Retour_commandLinkButton")
        self.Brand_Label = QtWidgets.QLabel(Form)
        self.Brand_Label.setGeometry(QtCore.QRect(280, 10, 171, 71))
        self.Brand_Label.setObjectName("Brand_Label")
        self.listepraticiens_Label = QtWidgets.QLabel(Form)
        self.listepraticiens_Label.setGeometry(QtCore.QRect(0, 120, 301, 41))
        self.listepraticiens_Label.setObjectName("listepraticiens_Label")
        self.ListePraticens_listWidget = QtWidgets.QListWidget(Form)
        self.ListePraticens_listWidget.setGeometry(QtCore.QRect(20, 190, 251, 331))
        self.ListePraticens_listWidget.setObjectName("ListePraticens_listWidget")
        item = QtWidgets.QListWidgetItem()
        self.ListePraticens_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListePraticens_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListePraticens_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListePraticens_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListePraticens_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListePraticens_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListePraticens_listWidget.addItem(item)
        self.Horaire_Label = QtWidgets.QLabel(Form)
        self.Horaire_Label.setGeometry(QtCore.QRect(400, 120, 291, 41))
        self.Horaire_Label.setObjectName("Horaire_Label")
        self.ValidationpushButton = QtWidgets.QPushButton(Form)
        self.ValidationpushButton.setGeometry(QtCore.QRect(310, 550, 111, 41))
        self.ValidationpushButton.setObjectName("ValidationpushButton")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(400, 200, 241, 22))
        self.comboBox.setObjectName("comboBox")
        self.Info_Label = QtWidgets.QLabel(Form)
        self.Info_Label.setGeometry(QtCore.QRect(400, 280, 291, 81))
        self.Info_Label.setObjectName("Info_Label")
        self.InfolineEdit = QtWidgets.QLineEdit(Form)
        self.InfolineEdit.setGeometry(QtCore.QRect(410, 380, 251, 31))
        self.InfolineEdit.setObjectName("InfolineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Retour_commandLinkButton.setText(_translate("Form", "Annuler"))
        self.Brand_Label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline;\">DoctObélix</span></p></body></html>"))
        self.listepraticiens_Label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Liste des praticiens disponibles :</span></p></body></html>"))
        __sortingEnabled = self.ListePraticens_listWidget.isSortingEnabled()
        self.ListePraticens_listWidget.setSortingEnabled(False)
        item = self.ListePraticens_listWidget.item(0)
        item.setText(_translate("Form", "New Item"))
        item = self.ListePraticens_listWidget.item(1)
        item.setText(_translate("Form", "New Item"))
        item = self.ListePraticens_listWidget.item(2)
        item.setText(_translate("Form", "New Item"))
        item = self.ListePraticens_listWidget.item(3)
        item.setText(_translate("Form", "New Item"))
        item = self.ListePraticens_listWidget.item(4)
        item.setText(_translate("Form", "New Item"))
        item = self.ListePraticens_listWidget.item(5)
        item.setText(_translate("Form", "New Item"))
        item = self.ListePraticens_listWidget.item(6)
        item.setText(_translate("Form", "New Item"))
        self.ListePraticens_listWidget.setSortingEnabled(__sortingEnabled)
        self.Horaire_Label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Horaires possibles :</span></p></body></html>"))
        self.ValidationpushButton.setText(_translate("Form", "Validation"))
        self.Info_Label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Informations supplémentaires :</span></p><p align=\"center\"><span style=\" font-size:12pt;\">(Pour le médecin)</span></p></body></html>"))
