# Form implementation generated from reading ui file 'c:\Users\Dartencet\Desktop\Sauvgarde ProjetInfo\Autre possibilitée\InscriptionPat.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys
from . import fonctions

class Ui_Form(object):
    def __init__(self,arg):
        self.arg = arg
        self.continuation = False
        self.nom_patient = ''
        self.prenom_patient = ''
        self.jour_patient = ''
        self.mois_patient = ''
        self.annee_patient = ''
        self.mail_patient = ''
        self.motdepasse_patient = ''
        self.numero_patient = ''


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 424)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 151, 51))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 40, 91, 51))
        self.label.setObjectName("label")
        self.Nomlabel = QtWidgets.QLabel(Form)
        self.Nomlabel.setGeometry(QtCore.QRect(20, 130, 121, 21))
        self.Nomlabel.setObjectName("Nomlabel")
        self.NomlineEdit = QtWidgets.QLineEdit(Form)
        self.NomlineEdit.setGeometry(QtCore.QRect(190, 130, 181, 21))
        self.NomlineEdit.setObjectName("NomlineEdit")
        self.PrenomlineEdit = QtWidgets.QLineEdit(Form)
        self.PrenomlineEdit.setGeometry(QtCore.QRect(190, 160, 181, 21))
        self.PrenomlineEdit.setObjectName("PrenomlineEdit")
        self.Prenomlabel = QtWidgets.QLabel(Form)
        self.Prenomlabel.setGeometry(QtCore.QRect(20, 160, 121, 21))
        self.Prenomlabel.setObjectName("Prenomlabel")
        self.DateNaissancelabel = QtWidgets.QLabel(Form)
        self.DateNaissancelabel.setGeometry(QtCore.QRect(20, 190, 161, 21))
        self.DateNaissancelabel.setObjectName("DateNaissancelabel")
        self.jourlineEdit = QtWidgets.QLineEdit(Form)
        self.jourlineEdit.setGeometry(QtCore.QRect(190, 190, 21, 21))
        self.jourlineEdit.setText("")
        self.jourlineEdit.setObjectName("jourlineEdit")
        self.AdresseMaillabel = QtWidgets.QLabel(Form)
        self.AdresseMaillabel.setGeometry(QtCore.QRect(20, 270, 121, 21))
        self.AdresseMaillabel.setObjectName("AdresseMaillabel")
        self.AdresseMaillineEdit = QtWidgets.QLineEdit(Form)
        self.AdresseMaillineEdit.setGeometry(QtCore.QRect(190, 270, 181, 21))
        self.AdresseMaillineEdit.setObjectName("AdresseMaillineEdit")
        self.ValidationpushButton = QtWidgets.QPushButton(Form)
        self.ValidationpushButton.setGeometry(QtCore.QRect(150, 370, 101, 41))
        self.ValidationpushButton.setObjectName("ValidationpushButton")
        self.Numerolabel = QtWidgets.QLabel(Form)
        self.Numerolabel.setGeometry(QtCore.QRect(20, 220, 161, 21))
        self.Numerolabel.setObjectName("Numerolabel")
        self.NumerolineEdit = QtWidgets.QLineEdit(Form)
        self.NumerolineEdit.setGeometry(QtCore.QRect(190, 220, 181, 21))
        self.NumerolineEdit.setObjectName("NumerolineEdit")
        self.MdPlineEdit = QtWidgets.QLineEdit(Form)
        self.MdPlineEdit.setGeometry(QtCore.QRect(190, 320, 181, 21))
        self.MdPlineEdit.setObjectName("MdPlineEdit")
        self.MdPlabel = QtWidgets.QLabel(Form)
        self.MdPlabel.setGeometry(QtCore.QRect(20, 320, 121, 21))
        self.MdPlabel.setObjectName("MdPlabel")
        self.moislineEdit = QtWidgets.QLineEdit(Form)
        self.moislineEdit.setGeometry(QtCore.QRect(220, 190, 21, 21))
        self.moislineEdit.setObjectName("moislineEdit")
        self.anneelineEdit = QtWidgets.QLineEdit(Form)
        self.anneelineEdit.setGeometry(QtCore.QRect(250, 190, 31, 21))
        self.anneelineEdit.setObjectName("anneelineEdit")
        self.jjmmaaaalabel = QtWidgets.QLabel(Form)
        self.jjmmaaaalabel.setGeometry(QtCore.QRect(290, 190, 91, 21))
        self.jjmmaaaalabel.setObjectName("jjmmaaaalabel")
        

        self.retranslateUi(Form)

        self.ValidationpushButton.released.connect(lambda: self.add(self.continuation, True))

        self.ValidationpushButton.released.connect(lambda: self.add(self.nom_patient, self.NomlineEdit.text()))
        self.ValidationpushButton.released.connect(lambda: self.add(self.prenom_patient, self.PrenomlineEdit.text()))
        self.ValidationpushButton.released.connect(lambda: self.add(self.jour_patient, self.jourlineEdit.text()))
        self.ValidationpushButton.released.connect(lambda: self.add(self.mois_patient, self.moislineEdit.text()))
        self.ValidationpushButton.released.connect(lambda: self.add(self.annee_patient, self.anneelineEdit.text()))
        self.ValidationpushButton.released.connect(lambda: self.add(self.numero_patient, self.NumerolineEdit.text()))
        self.ValidationpushButton.released.connect(lambda: self.add(self.mail_patient, self.AdresseMaillineEdit.text()))
        self.ValidationpushButton.released.connect(lambda: self.add(self.motdepasse_patient, self.MdPlineEdit.text()))

        self.ValidationpushButton.released.connect(Form.close) # type: ignore

        QtCore.QMetaObject.connectSlotsByName(Form)

    def add(self, var, arg):
        var = arg

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:italic; text-decoration: underline;\">DoctoLibre</span></p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-style:italic;\">Patient</span></p></body></html>"))
        self.Nomlabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Nom :</span></p></body></html>"))
        self.Prenomlabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Prénom :</span></p></body></html>"))
        self.DateNaissancelabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Date de naissance :</span></p></body></html>"))
        self.AdresseMaillabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Adresse Mail :</span></p></body></html>"))
        self.ValidationpushButton.setText(_translate("Form", "Validation"))
        self.Numerolabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Numéro :</span></p></body></html>"))
        self.MdPlabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Mot de Passe :</span></p></body></html>"))
        self.jjmmaaaalabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">jj/mm/aaaa</span></p><p><span style=\" font-size:9pt;\"><br/></span></p></body></html>"))

