# Form implementation generated from reading ui file 'c:\Users\Dartencet\Documents\GitHub\projetprogrammation2021\modules\IHM\IHM_en_Qt\4EdTDoc.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(720, 614)
        self.EdTtableView = QtWidgets.QTableView(Form)
        self.EdTtableView.setGeometry(QtCore.QRect(60, 200, 601, 331))
        self.EdTtableView.setObjectName("EdTtableView")
        self.EdT_Label = QtWidgets.QLabel(Form)
        self.EdT_Label.setGeometry(QtCore.QRect(220, 130, 281, 41))
        self.EdT_Label.setObjectName("EdT_Label")
        self.Brand_Label = QtWidgets.QLabel(Form)
        self.Brand_Label.setGeometry(QtCore.QRect(280, 0, 151, 71))
        self.Brand_Label.setObjectName("Brand_Label")
        self.FermepushButton = QtWidgets.QPushButton(Form)
        self.FermepushButton.setGeometry(QtCore.QRect(310, 560, 101, 41))
        self.FermepushButton.setObjectName("FermepushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.EdT_Label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Emploi du Temps :</span></p></body></html>"))
        self.Brand_Label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline;\">DoctObélix</span></p></body></html>"))
        self.FermepushButton.setText(_translate("Form", "Fermer"))
