# Form implementation generated from reading ui file 'c:\Users\Dartencet\Documents\GitHub\projetprogrammation2021\modules\IHM\IHM_en_Qt\4EdTPraticiens.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys
from . import fonctions

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(720, 615)
        self.Retour_commandLinkButton = QtWidgets.QCommandLinkButton(Form)
        self.Retour_commandLinkButton.setGeometry(QtCore.QRect(0, 520, 222, 48))
        self.Retour_commandLinkButton.setObjectName("Retour_commandLinkButton")
        self.Brand_Label = QtWidgets.QLabel(Form)
        self.Brand_Label.setGeometry(QtCore.QRect(280, 10, 171, 71))
        self.Brand_Label.setObjectName("Brand_Label")
        self.listepraticiens_Label = QtWidgets.QLabel(Form)
        self.listepraticiens_Label.setGeometry(QtCore.QRect(0, 120, 301, 41))
        self.listepraticiens_Label.setObjectName("listepraticiens_Label")
        self.ListePraticens_listView = QtWidgets.QListView(Form)
        self.ListePraticens_listView.setGeometry(QtCore.QRect(20, 190, 251, 331))
        self.ListePraticens_listView.setObjectName("ListePraticens_listView")
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(365, 190, 351, 331))
        self.tableView.setObjectName("tableView")
        self.EdTPraticien_Label = QtWidgets.QLabel(Form)
        self.EdTPraticien_Label.setGeometry(QtCore.QRect(400, 120, 291, 41))
        self.EdTPraticien_Label.setObjectName("EdTPraticien_Label")
        self.ValidationpushButton = QtWidgets.QPushButton(Form)
        self.ValidationpushButton.setGeometry(QtCore.QRect(260, 550, 111, 41))
        self.ValidationpushButton.setObjectName("ValidationpushButton")

        self.retranslateUi(Form)
        self.ListePraticens_listView.activated['QModelIndex'].connect(self.tableView.edit) # type: ignore
        self.tableView.activated['QModelIndex'].connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Retour_commandLinkButton.setText(_translate("Form", "Annuler"))
        self.Brand_Label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline;\">DoctObélix</span></p></body></html>"))
        self.listepraticiens_Label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Liste des praticiens disponibles :</span></p></body></html>"))
        self.EdTPraticien_Label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Emploi du Temps du Praticien :</span></p></body></html>"))
        self.ValidationpushButton.setText(_translate("Form", "Validation"))
