# Form implementation generated from reading ui file 'c:\Users\Dartencet\Documents\GitHub\projetprogrammation2021\modules\IHM\IHM_en_Qt\recap.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys


class Ui_Form(object):
    def __init__(self,arg):
        self.arg = arg
        
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 424)
        self.Brand_Label = QtWidgets.QLabel(Form)
        self.Brand_Label.setGeometry(QtCore.QRect(120, 10, 171, 71))
        self.Brand_Label.setObjectName("Brand_Label")
        self.Rdvlabel = QtWidgets.QLabel(Form)
        self.Rdvlabel.setGeometry(QtCore.QRect(30, 100, 151, 16))
        self.Rdvlabel.setObjectName("Rdvlabel")
        self.heurelabel = QtWidgets.QLabel(Form)
        self.heurelabel.setGeometry(QtCore.QRect(30, 140, 151, 16))
        self.heurelabel.setObjectName("heurelabel")
        self.nomdoclabel = QtWidgets.QLabel(Form)
        self.nomdoclabel.setGeometry(QtCore.QRect(30, 180, 111, 16))
        self.nomdoclabel.setObjectName("nomdoclabel")
        self.adresselabel = QtWidgets.QLabel(Form)
        self.adresselabel.setGeometry(QtCore.QRect(30, 220, 55, 16))
        self.adresselabel.setObjectName("adresselabel")
        self.villelabel = QtWidgets.QLabel(Form)
        self.villelabel.setGeometry(QtCore.QRect(100, 250, 55, 16))
        self.villelabel.setObjectName("villelabel")
        self.ruelabel = QtWidgets.QLabel(Form)
        self.ruelabel.setGeometry(QtCore.QRect(100, 230, 55, 16))
        self.ruelabel.setObjectName("ruelabel")
        self.codepostallabel = QtWidgets.QLabel(Form)
        self.codepostallabel.setGeometry(QtCore.QRect(100, 270, 81, 16))
        self.codepostallabel.setObjectName("codepostallabel")
        self.numerolabel = QtWidgets.QLabel(Form)
        self.numerolabel.setGeometry(QtCore.QRect(30, 310, 55, 16))
        self.numerolabel.setObjectName("numerolabel")
        self.adressemaillabel = QtWidgets.QLabel(Form)
        self.adressemaillabel.setGeometry(QtCore.QRect(30, 350, 91, 16))
        self.adressemaillabel.setObjectName("adressemaillabel")
        self.infolabel = QtWidgets.QLabel(Form)
        self.infolabel.setGeometry(QtCore.QRect(30, 390, 151, 16))
        self.infolabel.setObjectName("infolabel")
        self.rdvmodiflabel = QtWidgets.QLabel(Form)
        self.rdvmodiflabel.setGeometry(QtCore.QRect(190, 100, 211, 20))
        self.rdvmodiflabel.setObjectName("rdvmodiflabel")
        self.heuremodiflabel = QtWidgets.QLabel(Form)
        self.heuremodiflabel.setGeometry(QtCore.QRect(190, 140, 211, 16))
        self.heuremodiflabel.setObjectName("heuremodiflabel")
        self.nomdocmodiflabel = QtWidgets.QLabel(Form)
        self.nomdocmodiflabel.setGeometry(QtCore.QRect(190, 180, 211, 16))
        self.nomdocmodiflabel.setObjectName("nomdocmodiflabel")
        self.villemodiflabel = QtWidgets.QLabel(Form)
        self.villemodiflabel.setGeometry(QtCore.QRect(200, 250, 201, 16))
        self.villemodiflabel.setObjectName("villemodiflabel")
        self.codepostalmodiflabel = QtWidgets.QLabel(Form)
        self.codepostalmodiflabel.setGeometry(QtCore.QRect(200, 270, 201, 16))
        self.codepostalmodiflabel.setObjectName("codepostalmodiflabel")
        self.ruemodiflabel = QtWidgets.QLabel(Form)
        self.ruemodiflabel.setGeometry(QtCore.QRect(200, 230, 201, 16))
        self.ruemodiflabel.setObjectName("ruemodiflabel")
        self.numeromodiflabel = QtWidgets.QLabel(Form)
        self.numeromodiflabel.setGeometry(QtCore.QRect(190, 310, 211, 16))
        self.numeromodiflabel.setObjectName("numeromodiflabel")
        self.adressemailmodiflabel = QtWidgets.QLabel(Form)
        self.adressemailmodiflabel.setGeometry(QtCore.QRect(190, 350, 211, 16))
        self.adressemailmodiflabel.setObjectName("adressemailmodiflabel")
        self.infodonneesmodiflabel = QtWidgets.QLabel(Form)
        self.infodonneesmodiflabel.setGeometry(QtCore.QRect(190, 390, 211, 16))
        self.infodonneesmodiflabel.setObjectName("infodonneesmodiflabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Brand_Label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline;\">DoctObélix</span></p></body></html>"))
        self.Rdvlabel.setText(_translate("Form", "Date du Rendez-Vous :"))
        self.heurelabel.setText(_translate("Form", "Heure du Rendez-Vous :"))
        self.nomdoclabel.setText(_translate("Form", "Nom du médecin :"))
        self.adresselabel.setText(_translate("Form", "Adresse :"))
        self.villelabel.setText(_translate("Form", "Ville :"))
        self.ruelabel.setText(_translate("Form", "Rue :"))
        self.codepostallabel.setText(_translate("Form", "Code postal :"))
        self.numerolabel.setText(_translate("Form", "Numéro :"))
        self.adressemaillabel.setText(_translate("Form", "Adresse mail :"))
        self.infolabel.setText(_translate("Form", "Informations données :"))
        self.rdvmodiflabel.setText(_translate("Form", "TextLabel"))
        self.heuremodiflabel.setText(_translate("Form", "TextLabel"))
        self.nomdocmodiflabel.setText(_translate("Form", "TextLabel"))
        self.villemodiflabel.setText(_translate("Form", "TextLabel"))
        self.codepostalmodiflabel.setText(_translate("Form", "TextLabel"))
        self.ruemodiflabel.setText(_translate("Form", "TextLabel"))
        self.numeromodiflabel.setText(_translate("Form", "TextLabel"))
        self.adressemailmodiflabel.setText(_translate("Form", "TextLabel"))
        self.infodonneesmodiflabel.setText(_translate("Form", "TextLabel"))
